esphome:
  name: nuclear

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MpKke9/YDOnrgDYMoafoQxPlNhZxCkVhAYbbZdhT2XA="

ota:
  password: "44f6ac6b430e766aa14c844fbd912d6b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nuclear Fallback Hotspot"
    password: "z1Hx5mBQ4bMV"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifi_sensor

  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor

binary_sensor:
  - platform: gpio
    name: "Page 1"
    pin:
      number: 38
    on_press:
      then:
        - display.page.show: page1

  - platform: gpio
    name: "Page 2"
    pin:
      number: 37
    on_press:
      then:
        - display.page.show: page2

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 12

display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 27
    dc_pin: 32
    led_pin: 4 ### see note below ###
    reset_pin: 5
    rotation: 270
    pages:
      - id: page1
        lambda: |-
          // Draw the graph at position [x=10,y=20]
          it.graph(10, 20, id(single_temperature_graph));
      - id: page2
        lambda: |-
          // Draw the graph at position [x=10,y=20]
          it.graph(10, 20, id(multi_temperature_graph), my_yellow);

color:
  - id: my_light_red
    red: 100%
    green: 20%
    blue: 25%
    white: 0%

  - id: my_light_blue
    red: 25%
    green: 20%
    blue: 100%
    white: 0%

  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%

graph:
  # Show bare-minimum auto-ranged graph
  - id: single_temperature_graph
    sensor: wifi_sensor
    duration: 1h
    width: 300
    height: 200
  - id: multi_temperature_graph
    sensor: uptime_sensor
    duration: 1h
    width: 300
    height: 200
  # Show multi-trace graph
  # - id: multi_temperature_graph
  #   duration: 1h
  #   width: 300
  #   height: 200
  #   max_value: -100.
  #   min_value: 1000.
  #   traces:
  #     - sensor: uptime_sensor
  #       line_type: DASHED
  #       line_thickness: 2
  #       color: my_light_red
  #     - sensor: wifi_sensor
  #       line_type: SOLID
  #       line_thickness: 3
  #       color: my_light_blue
