esphome:
  name: nuclear

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MpKke9/YDOnrgDYMoafoQxPlNhZxCkVhAYbbZdhT2XA="

ota:
  password: "44f6ac6b430e766aa14c844fbd912d6b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nuclear Fallback Hotspot"
    password: "z1Hx5mBQ4bMV"

captive_portal:

sensor:
  - platform: pulse_counter
    pin: 19
    unit_of_measurement: "CPM"
    name: "Ionizing Radiation Counts Per Minute"
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    update_interval: 60s
    accuracy_decimals: 3
    id: counter_cpm
    filters:
      - sliding_window_moving_average: # 5-minutes moving average (MA5) here
          window_size: 5
          send_every: 5

  - platform: integration
    name: "Ionizing Radiation Power"
    unit_of_measurement: "μSv/h"
    sensor: counter_cpm # link entity id to the pulse_counter values above
    id: counter_uSv_h
    icon: "mdi:radioactive"
    accuracy_decimals: 5
    time_unit: min # integrate values every next minute
    filters:
      - multiply: 0.0057

binary_sensor:
  - platform: gpio
    name: "Page 1"
    pin:
      number: 38
    on_press:
      then:
        - display.page.show: page1

  - platform: gpio
    name: "Page 2"
    pin:
      number: 37
    on_press:
      then:
        - display.page.show: page2

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto22
    size: 25
    glyphs: ["μ", "S", "v", "/", "h", "C", "M", "P"]
  - file: "gfonts://Roboto"
    id: roboto36
    size: 36
  - file: "gfonts://Roboto"
    id: roboto40
    size: 40

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 12

display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 27
    dc_pin: 32
    led_pin: 4 ### see note below ###
    reset_pin: 5
    rotation: 270
    pages:
      - id: page1
        lambda: |-
          id(my_animation).next_frame();
          it.image(20, 10, id(my_animation));
          it.print(100, 10, id(roboto40), my_yellow, "Radiation");
          it.printf(5, 80, id(roboto36), "%.3f", id(counter_uSv_h).state);
          it.print(100, 140, id(roboto22), TextAlign::BASELINE_RIGHT, "μSv/h");
          it.printf(5, 160, id(roboto36), "%.0f", id(counter_cpm).state);
          it.print(100, 220, id(roboto22), TextAlign::BASELINE_RIGHT, "CPM");
          it.graph(115, 70, id(uSv_Hour_graph), my_light_blue);
          it.graph(115, 155, id(cpm_graph), my_yellow);
      - id: page2
        lambda: |-
          it.print(20, 100, id(roboto22), "Hello World!");

animation:
  - file: "radio.gif"
    id: my_animation
    resize: 50x50
    type: RGB24

color:
  - id: my_light_red
    red: 100%
    green: 20%
    blue: 25%
    white: 0%

  - id: my_light_blue
    red: 25%
    green: 20%
    blue: 100%
    white: 0%

  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%

graph:
  # Show bare-minimum auto-ranged graph
  - id: uSv_Hour_graph
    sensor: counter_uSv_h
    duration: 1h
    width: 200
    height: 80
  - id: cpm_graph
    sensor: counter_cpm
    duration: 1h
    width: 200
    height: 80
